# Generated by Django 5.0.2 on 2024-03-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='probability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
